#!/usr/bin/env node
const { Octokit } = require("@octokit/rest");
const simpleGit = require('simple-git');
const git = simpleGit();
const fs = require('fs');

async function main() {
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  const remote = process.env.GIT_REMOTE || 'origin';
  const base = process.env.PR_BASE || 'main';

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const branch = `autopr/rio-press-${timestamp}`;

  try {
    await git.checkoutLocalBranch(branch);
    await git.add('./*');
    const status = await git.status();
    if (status.staged.length === 0 && status.modified.length === 0 && status.created.length === 0) {
      console.log('No changes to commit.');
      process.exit(0);
    }
    await git.commit(`chore: auto PR - add Rio International Press and related UI updates`);
    console.log(`Committed changes on ${branch}`);
    await git.push(remote, branch, {'--set-upstream': null});
    console.log(`Pushed branch ${branch} to ${remote}`);

    if (!token) {
      console.log('No GITHUB_TOKEN found. Skipping PR creation. Set GITHUB_TOKEN to create PR automatically.');
      process.exit(0);
    }

    const octokit = new Octokit({ auth: token });
    const repo = process.env.GITHUB_REPOSITORY;
    if (!repo) {
      console.log('GITHUB_REPOSITORY not set (owner/repo). Skipping PR creation.');
      process.exit(0);
    }
    const [owner, repoName] = repo.split('/');

    const pr = await octokit.pulls.create({
      owner,
      repo: repoName,
      title: 'Auto PR: Rio International Press & UI updates',
      head: branch,
      base,
      body: 'Automated PR generated by local `scripts/auto-pr.js` to add Rio International Press, hide Clippings, update login button color and add Firestore sync script.'
    });

    console.log('PR created:', pr.data.html_url);
  } catch (e) {
    console.error('Auto PR failed', e.message || e);
    process.exit(1);
  }
}

main();
